# Generated by Django 2.2.6 on 2019-10-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
