# Generated by Django 2.2.6 on 2019-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_delete_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='desc',
            field=models.TextField(),
        ),
    ]
